version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - ci
      - dependencies
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
