######################################################################################
# Idefix MHD astrophysical code
#
# Source file ruff.toml
#
# Last modified : 07/2026
#
# Copyright(C) by :
# - Clément Robert <clement.robert@univ-grenoble-alpes.fr> (IPAG/UGA/CNRS - 2026)
# and other code contributors
#
# Licensed under CeCILL 2.1 License, see COPYING for more information
######################################################################################

target-version = "py310"

[lint]
select = [
    "F",    # pyflakes
    "B",    # flake8-bugbear
    "I",    # isort
    "NPY",  # numpy-specific rules
]
ignore = [
    # allow `import *`
    "F403", # undefined-local-with-import-star
    "F405", # undefined-local-with-import-star-usage
]
