# TODO: One could speed up compilation by compiling only the module compatible with HD/MHD

INCLUDE_DIR += -I$(SRC)/hydro/HDsolvers -I$(SRC)/hydro/MHDsolvers
VPATH += $(SRC)/hydro/HDsolvers $(SRC)/hydro/MHDsolvers
HEADERS += solversHD.hpp solversMHD.hpp
OBJ += hllcHD.o hllHD.o roeHD.o tvdlfHD.o hlldMHD.o hllMHD.o roeMHD.o tvdlfMHD.o
