name: Question
description: Ask a question
title: "<Please write a comprehensive title>"
labels: [question]

body:
- type: markdown
  attributes:
    value: >
      Thank you for taking the time to file your question.
  validations:
    required: true
