#!/usr/bin/env bash
######################################################################################
# Idefix MHD astrophysical code
#
# Source file scripts/ci/run-tests
#
# Last modified : 06/2026
#
# Copyright(C) by :
# - Marc Coiffier <marc.coiffier@univ-grenoble-alpes.fr> (IPAG/UGA/CNRS - 2024)
# - Geoffroy Lesur <geoffroy.lesur@univ-grenoble-alpes.fr> (IPAG/UGA/CNRS - 2026)
# - Sébastien Valat <sebastien.valat@univ-grenoble-alpes.fr> (IPAG/UGA/CNRS - 2026)
# and other code contributors
#
# Licensed under CeCILL 2.1 License, see COPYING for more information
######################################################################################

# load ICC compiler env
if [ "$IDEFIX_COMPILER" == icc ]; then
    source /opt/intel/oneapi/setvars.sh
fi

# enable bash features
set -ue

# load python venv if present
if [ -d .venv ]; then
    source .venv/bin/activate
fi

# to get access to idefix ./pytools/ module in python code
if [[ -v PYTHONPATH ]]; then
    export PYTHONPATH="${PWD}:${PYTHONPATH}"
else
    export PYTHONPATH="${PWD}"
fi

# run the test the old way (still possible up to now)
#cd "$1"
#./testme.py "${@:2}"

# run the test the new way (via pytest)
./test.py -subdir "$@"
